# Generated by Django 3.1.6 on 2023-04-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='addedDate',
            field=models.DateField(default='2023-04-17'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='dueDate',
            field=models.DateField(default='2023-04-17'),
        ),
    ]
